import { TPageConfig } from "@/models";

export const PAGES_CONFIG: TPageConfig = {
  slug: "",
  template: "home",
  backgroundImage: "fdn-liliana-dreadhorde-general-dmitry-burmak",
  backgroundCaption: "Dmitry Burmak",
  description: "Reference strategy guides and tools for limited Magic: The Gathering.",
  pages: [
    {
      slug: "not-found",
      template: "not-found",
      backgroundImage: "m19-totally-lost-david-palumbo",
      backgroundCaption: "David Palumbo",
      title: "Not Found",
      description: "That page could not be found.",
    },
    {
      slug: "directory",
      template: "directory",
      backgroundImage: "ulg-frantic-search-jeff-miracola",
      backgroundCaption: "Jeff Miracola",
      title: "Format Directory",
      description: "A full directory of all formats available on MTG Primer.",
    },
    {
      slug: "pioneer-masters",
      template: "info",
      preset: "info",
      formatCode: "pio",
      releaseDate: "December 10th, 2024",
      backgroundImage: "pio-heliod-god-of-the-sun-jaime-jones",
      backgroundCaption: "Jaime Jones",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "pio-heliod-god-of-the-sun-jaime-jones",
          backgroundCaption: "Jaime Jones",
        },
        {
          slug: "removal",
          template: "guide-group",
          preset: "guide-group-removal",
          guideGroup: "removal",
          backgroundImage: "pio-heliod-god-of-the-sun-jaime-jones",
          backgroundCaption: "Jaime Jones",
        },
        {
          slug: "effects",
          template: "guide-group",
          preset: "guide-group-effects",
          guideGroup: "effects",
          backgroundImage: "pio-heliod-god-of-the-sun-jaime-jones",
          backgroundCaption: "Jaime Jones",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "pio-heliod-god-of-the-sun-jaime-jones",
          backgroundCaption: "Jaime Jones",
        },
      ],
    },
    {
      slug: "foundations",
      template: "info",
      preset: "info",
      formatCode: "fdn",
      releaseDate: "November 15th, 2024",
      backgroundImage: "fdn-liliana-dreadhorde-general-dmitry-burmak",
      backgroundCaption: "Dmitry Burmak",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "fdn-liliana-dreadhorde-general-dmitry-burmak",
          backgroundCaption: "Dmitry Burmak",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "fdn-liliana-dreadhorde-general-dmitry-burmak",
          backgroundCaption: "Dmitry Burmak",
        },
      ],
    },
    {
      slug: "duskmourn",
      template: "info",
      preset: "info",
      formatCode: "dsk",
      releaseDate: "September 27th, 2024",
      backgroundImage: "dsk-overlord-of-the-hauntwoods-aogachou",
      backgroundCaption: "Aogachou",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "dsk-overlord-of-the-hauntwoods-aogachou",
          backgroundCaption: "Aogachou",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "dsk-overlord-of-the-hauntwoods-aogachou",
          backgroundCaption: "Aogachou",
        },
      ],
    },
    {
      slug: "bloomburrow",
      template: "info",
      preset: "info",
      formatCode: "blb",
      releaseDate: "July 30th, 2024",
      backgroundImage: "blb-maha-its-feathers-night-alessandra-pisano",
      backgroundCaption: "Alessandra Pisano",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "blb-maha-its-feathers-night-alessandra-pisano",
          backgroundCaption: "Alessandra Pisano",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "blb-maha-its-feathers-night-alessandra-pisano",
          backgroundCaption: "Alessandra Pisano",
        },
      ],
    },
    {
      slug: "modern-horizons-3",
      template: "info",
      preset: "info",
      formatCode: "mh3",
      releaseDate: "June 14, 2024",
      backgroundImage: "mh3-emrakul-the-world-anew-brent-hollowell",
      backgroundCaption: "Brent Hollowell",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "mh3-emrakul-the-world-anew-brent-hollowell",
          backgroundCaption: "Brent Hollowell",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "mh3-emrakul-the-world-anew-brent-hollowell",
          backgroundCaption: "Brent Hollowell",
        },
      ],
    },
    {
      slug: "outlaws-of-thunder-junction",
      template: "info",
      preset: "info",
      formatCode: "otj",
      releaseDate: "April 16, 2024",
      backgroundImage: "otj-colossal-rattlewurm-Filip-burburan",
      backgroundCaption: "Filip Burburan",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "otj-colossal-rattlewurm-Filip-burburan",
          backgroundCaption: "Filip Burburan",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "otj-colossal-rattlewurm-Filip-burburan",
          backgroundCaption: "Filip Burburan",
        },
      ],
    },
    {
      slug: "murders-at-karlov-manor",
      template: "info",
      preset: "info",
      formatCode: "mkm",
      releaseDate: "February 6, 2024",
      backgroundImage: "mkm-demand-answers-justyna-dura",
      backgroundCaption: "Justyna Dura",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "mkm-not-on-my-watch-jason-a-engle",
          backgroundCaption: "Jason A. Engle",
        },
        {
          slug: "disguise",
          template: "guide",
          guide: "disguise",
          title: "Disguise Guide",
          description: "A guide to every possible disguise card.",
          icon: "fas fa-mask",
          backgroundImage: "mkm-kaya-spirits-justice-magali-villeneuve",
          backgroundCaption: "Magali Villeneuve",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "mkm-teysa-opulent-oligarch-chris-rallis",
          backgroundCaption: "Chris Rallis",
        },
      ],
    },
    {
      slug: "the-lost-caverns-of-ixalan",
      template: "info",
      preset: "info",
      formatCode: "lci",
      releaseDate: "November 14, 2023",
      backgroundImage: "lci-treasure-cove-nestor-ossandon-leal",
      backgroundCaption: "Ossandon Leal",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "lci-xolatoyac-the-smiling-flood-campbell-white",
          backgroundCaption: "Campbell White",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "lci-temple-of-cyclical-time-chris-rahn",
          backgroundCaption: "Chris Rahn",
        },
      ],
    },
    {
      slug: "wilds-of-eldraine",
      template: "info",
      preset: "info",
      formatCode: "woe",
      releaseDate: "September 8, 2023",
      backgroundImage: "woe-solitary-sanctuary-kasia-kafis-zielinska",
      backgroundCaption: "Kasia 'Kafis' Zielińska",
      pages: [
        {
          slug: "effects",
          template: "guide-group",
          guideGroup: "effects",
          preset: "guide-group-effects",
          backgroundImage: "woe-yenna-redtooth-regent-justyna-dura",
          backgroundCaption: "Justyna Dura",
        },
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "woe-pollen-shield-hare-olena-richards",
          backgroundCaption: "Olena Richards",
        },
        {
          slug: "interaction",
          template: "guide",
          preset: "guide-interaction",
          guide: "interaction",
          backgroundImage: "woe-three-bowls-of-porridge-edgar-sanchez-hidalgo",
          backgroundCaption: "Edgar Sánchez Hidalgo",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "woe-warehouse-tabby-steve-prescott",
          backgroundCaption: "Steve Prescott",
        },
      ],
    },
    {
      slug: "the-lord-of-the-rings-tales-of-middle-earth",
      template: "info",
      preset: "info",
      formatCode: "ltr",
      releaseDate: "June 20, 2023",
      backgroundImage: "ltr-barad-dur-sean-vo",
      backgroundCaption: "Sean Vo",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "ltr-battle-of-pelennor-fields-tyler-jacobson",
          backgroundCaption: "Tyler Jacobson",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "ltr-samwise-gamgee-ekaterina-burmak",
          backgroundCaption: "Ekaterina Burmak",
        },
      ],
    },
    {
      slug: "march-of-the-machine",
      template: "info",
      preset: "info",
      formatCode: "mom",
      releaseDate: "April 18, 2023",
      backgroundImage: "mom-elesh-norn-ryan-pancoast",
      backgroundCaption: "Ryan Pancoast",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "mom-sheoldred-camille-alquier",
          backgroundCaption: "Camille Alquier",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "mom-order-of-the-alabaster-host-andrew-mar",
          backgroundCaption: "Andrew Mar",
        },
      ],
    },
    {
      slug: "shadows-over-innistrad-remastered",
      template: "info",
      preset: "info",
      formatCode: "sir",
      releaseDate: "March 21, 2023",
      backgroundImage: "emn-emrakul-the-promised-end-jaime-jones",
      backgroundCaption: "Jaime Jones",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "soi-lightning-axe-jason-a-engle",
          backgroundCaption: "Jason A. Engle",
        },
        {
          slug: "madness",
          template: "guide",
          guide: "madness",
          title: "Madness Guide",
          description: "A guide to madness cards that can be cast when discarded.",
          icon: "fas fa-angry",
          backgroundImage: "soi-lightning-axe-jason-a-engle",
          backgroundCaption: "Jason A. Engle",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "emn-brisela-voice-of-nightmares-clint-cearley",
          backgroundCaption: "Clint Cearley",
        },
      ],
    },
    {
      slug: "phyrexia-all-will-be-one",
      template: "info",
      preset: "info",
      formatCode: "one",
      releaseDate: "February 7, 2023",
      backgroundImage: "one-ixhel-scion-of-atraxa-campbell-white",
      backgroundCaption: "Campbell White",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "one-red-suns-twilight-julian-kok-joon-wen",
          backgroundCaption: "Julian Kok Joon Wen",
        },
        {
          slug: "interaction",
          template: "guide",
          preset: "guide-interaction",
          guide: "interaction",
          backgroundImage: "one-evolved-spinoderm-svetlin-velinov",
          backgroundCaption: "Svetlin Velinov",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "one-vanish-into-eternity-magali-villeneuve",
          backgroundCaption: "Magali Villeneuve",
        },
      ],
    },
    {
      slug: "the-brothers-war",
      template: "info",
      preset: "info",
      formatCode: "bro",
      releaseDate: "November 15, 2022",
      backgroundImage: "bro-urza-planeswalker-ryan-pancoast",
      backgroundCaption: "Ryan Pancoast",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "bro-one-with-the-multiverse-liiga-smilshkalne",
          backgroundCaption: "Liiga Smilshkalne",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "bro-warlords-elite-joshua-raphael",
          backgroundCaption: "Joshua Raphael",
        },
      ],
    },
    {
      slug: "dominaria-united",
      template: "info",
      preset: "info",
      formatCode: "dmu",
      releaseDate: "September 1, 2022",
      backgroundImage: "dmu-squee-dubious-monarch-zoltan-boros",
      backgroundCaption: "Zoltan Boros",
      pages: [
        {
          slug: "effects",
          template: "guide-group",
          guideGroup: "effects",
          preset: "guide-group-effects",
          backgroundImage: "dmu-vodalian-mindsinger-steve-prescott",
          backgroundCaption: "Steve Prescott",
        },
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "dmu-sulfurous-springs-bruce-brenneise",
          backgroundCaption: "Bruce Brenneise",
        },
        /*{
          slug: "removal",
          template: "guide",
          preset: "guide-interaction",
          guide: "removal",
          backgroundImage: "dmu-lagomos-hand-of-hatred-tuan-duong-chu",
          backgroundCaption: "Tuan Duong Chu",
        },*/
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "dmu-sheoldred-the-apocalypse-joe-esposito",
          backgroundCaption: "Joe Esposito",
        },
      ],
    },
    {
      slug: "alchemy-horizons-baldurs-gate",
      template: "info",
      preset: "info",
      formatCode: "hbg",
      releaseDate: "July 7, 2022",
      backgroundImage: "hbg-baldurs-gate-titus-lunter",
      backgroundCaption: "Titus Lunter",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "hbg-wilson-refined-grizzly-ilse-gort",
          backgroundCaption: "Ilse Gort",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "hbg-forest-julian-kok-joon-wen",
          backgroundCaption: "Julian Kok Joon Wen",
        },
      ],
    },
    {
      slug: "double-masters-2022",
      template: "info",
      preset: "info",
      formatCode: "2x2",
      releaseDate: "June 30, 2022",
      backgroundImage: "2x2-imperial-seal-mark-tedin",
      backgroundCaption: "Mark Tedin",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "2x2-hardened-scales-jim-nelson",
          backgroundCaption: "Jim Nelson",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "2x2-senseis-divining-top-greg-staples",
          backgroundCaption: "Greg Staples",
        },
      ],
    },

    {
      slug: "streets-of-new-capenna",
      template: "info",
      preset: "info",
      formatCode: "snc",
      releaseDate: "April 10, 2022",
      backgroundImage: "snc-mountain-adam-paquette",
      backgroundCaption: "Adam Paquette",
      pages: [
        {
          slug: "effects",
          template: "guide-group",
          guideGroup: "effects",
          preset: "guide-group-effects",
          backgroundImage: "snc-xanders-lounge-james-paick",
          backgroundCaption: "James Paick",
        },
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "snc-a-litte-chat-matt-stewart",
          backgroundCaption: "Matt Stewart",
        },
        /*{
          slug: "removal",
          template: "guide",
          preset: "guide-interaction",
          guide: "removal",
          backgroundImage: "snc-pyre-sledge-arsonist-kekai-kotaki",
          backgroundCaption: "Kekai Kotaki",
        },*/
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "snc-hoard-hauler-jake-murray",
          backgroundCaption: "Jake Murray",
        },
      ],
    },
    {
      slug: "kamigawa-neon-dynasty",
      template: "info",
      preset: "info",
      formatCode: "neo",
      releaseDate: "February 10, 2022",
      backgroundImage: "neo-boseiju-who-endures-chris-ostrowski",
      backgroundCaption: "Chris Ostrowski",
      pages: [
        {
          slug: "effects",
          template: "guide-group",
          guideGroup: "effects",
          preset: "guide-group-effects",
          backgroundImage: "neo-enormous-energy-blade-campbell-white",
          backgroundCaption: "Campbell White",
        },
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "neo-storyweave-rovina-cai",
          backgroundCaption: "Rovina Cai",
        },
        // {
        //   slug: "removal",
        //   template: "guide",
        //   preset: "guide-interaction",
        //   guide: "removal",
        //   backgroundImage: "neo-march-of-otherworldly-light-nils-hamm",
        //   backgroundCaption: "Nils Hamm",
        // },
        {
          slug: "ninjutsu",
          template: "guide",
          guide: "ninjutsu",
          title: "Ninjutsu Guide",
          description: "A guide to every ninjutsu card in the format.",
          icon: "fas fa-user-ninja",
          backgroundImage: "neo-coiling-stalker-svetlin-velinov",
          backgroundCaption: "Svetlin Velinov",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "neo-simian-sling-nicholas-elias",
          backgroundCaption: "Nicholas Elias",
        },
      ],
    },
    {
      slug: "innistrad-double-feature",
      template: "info",
      preset: "info",
      formatCode: "dbl",
      releaseDate: "January 28, 2022",
      backgroundImage: "mid-unnatural-growth-svetlin-velinov",
      backgroundCaption: "Svetlin Velinov",
      pages: [
        {
          slug: "effects",
          template: "guide-group",
          guideGroup: "effects",
          preset: "guide-group-effects",
          backgroundImage: "vow-kindly-ancestor-justyna-gil",
          backgroundCaption: "Justyna Gil",
        },
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "vow-rending-flame-olena-richards",
          backgroundCaption: "Olena Richards",
        },
        // {
        //   slug: "removal",
        //   template: "guide",
        //   preset: "guide-interaction",
        //   guide: "removal",
        //   backgroundImage: "vow-kessig-wolfrider-bram-sels",
        //   backgroundCaption: "Bram Sels",
        // },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "mid-ludevic-necrogenius-ryan-pancoast",
          backgroundCaption: "Ryan Pancoast",
        },
      ],
    },
    {
      slug: "innistrad-crimson-vow",
      template: "info",
      preset: "info",
      formatCode: "vow",
      releaseDate: "November 11, 2021",
      backgroundImage: "vow-voldaren-estate-richard-wright",
      backgroundCaption: "Richard Wright",
      pages: [
        {
          slug: "effects",
          template: "guide-group",
          guideGroup: "effects",
          preset: "guide-group-effects",
          backgroundImage: "vow-kindly-ancestor-justyna-gil",
          backgroundCaption: "Justyna Gil",
        },
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "vow-rending-flame-olena-richards",
          backgroundCaption: "Olena Richards",
        },
        // {
        //   slug: "removal",
        //   template: "guide",
        //   preset: "guide-interaction",
        //   guide: "removal",
        //   backgroundImage: "vow-kessig-wolfrider-bram-sels",
        //   backgroundCaption: "Bram Sels",
        // },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "vow-faithbound-judge-svetlin-velinov",
          backgroundCaption: "Svetlin Velinov",
        },
      ],
    },
    {
      slug: "innistrad-midnight-hunt",
      template: "info",
      preset: "info",
      formatCode: "mid",
      releaseDate: "September 16, 2021",
      backgroundImage: "mid-duel-for-dominance-ryan-pancoast",
      backgroundCaption: "Ryan Pancoast",
      pages: [
        {
          slug: "effects",
          template: "guide-group",
          guideGroup: "effects",
          preset: "guide-group-effects",
          backgroundImage: "mid-seafaring-werewolf-jake-murray",
          backgroundCaption: "Jake Murray",
        },
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "mid-ludevic-necrogenius-ryan-pancoast",
          backgroundCaption: "Ryan Pancoast",
        },
        // {
        //   slug: "removal",
        //   template: "guide",
        //   preset: "guide-interaction",
        //   guide: "removal",
        //   backgroundImage: "mid-archive-haunt-cristi-balanescu",
        //   backgroundCaption: "Cristi Balanescu",
        // },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "mid-insectile-aberration-matt-stewart",
          backgroundCaption: "Matt Stewart",
        },
      ],
    },
    {
      slug: "adventures-in-the-forgotten-realms",
      template: "info",
      preset: "info",
      formatCode: "afr",
      releaseDate: "July 7, 2021",
      backgroundImage: "afr-xanathar-guild-kingpin-kieran-yanner",
      backgroundCaption: "Kieran Yanner",
      pages: [
        {
          slug: "effects",
          template: "guide-group",
          guideGroup: "effects",
          preset: "guide-group-effects",
          backgroundImage: "afr-lurking-roper-andrew-mar",
          backgroundCaption: "Andrew Mar",
        },
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "afr-you-see-a-pair-of-goblins-aaron-miller",
          backgroundCaption: "Aaron Miller",
        },
        // {
        //   slug: "removal",
        //   template: "guide",
        //   preset: "guide-interaction",
        //   guide: "removal",
        //   backgroundImage: "afr-meteor-swarm-olivier-bernard",
        //   backgroundCaption: "Olivier Bernard",
        // },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "afr-ebondeath-dracolich-lars-grant-west",
          backgroundCaption: "Lars Grant West",
        },
      ],
    },
    {
      slug: "modern-horizons-2",
      template: "info",
      preset: "info",
      formatCode: "mh2",
      releaseDate: "June 18, 2021",
      backgroundImage: "mh2-ragavan-nimble-pilferer-simon-dominic",
      backgroundCaption: "Simon Dominic",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "mh2-brainstone-drew-tucker",
          backgroundCaption: "Drew Tucker",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "mh2-chitterspitter-jason-felix",
          backgroundCaption: "Jason Felix",
        },
      ],
    },
    {
      slug: "strixhaven",
      template: "info",
      preset: "info",
      formatCode: "stx",
      releaseDate: "April 23, 2021",
      backgroundImage: "stx-archway-commons-piotr-dura",
      backgroundCaption: "Piotr Dura",
      pages: [
        {
          slug: "effects",
          template: "guide-group",
          guideGroup: "effects",
          preset: "guide-group-effects",
          backgroundImage: "stx-mage-hunter-mathias-kollros",
          backgroundCaption: "Mathias Kollros",
        },
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "stx-double-major-suzanne-helmigh",
          backgroundCaption: "Suzanne Helmigh",
        },
        // {
        //   slug: "removal",
        //   template: "guide",
        //   preset: "guide-interaction",
        //   guide: "removal",
        //   backgroundImage: "stx-awaken-the-blood-avatar-kekai-kotaki",
        //   backgroundCaption: "Kekai Kotaki",
        // },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "stx-shadrix-silverquill-kekai-kotaki",
          backgroundCaption: "Kekai Kotaki",
        },
      ],
    },
    {
      slug: "kaldheim",
      template: "info",
      preset: "info",
      formatCode: "khm",
      releaseDate: "January 28, 2021",
      backgroundImage: "khm-skemfar-avenger-randy-vargas",
      backgroundCaption: "Randy Vargas",
      pages: [
        {
          slug: "effects",
          template: "guide-group",
          guideGroup: "effects",
          preset: "guide-group-effects",
          backgroundImage: "khm-cosmos-charger-nils-hamm",
          backgroundCaption: "Nils Hamm",
        },
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "khm-demon-bolt-campbell-white",
          backgroundCaption: "Campbell White",
        },
        // {
        //   slug: "removal",
        //   template: "guide",
        //   preset: "guide-interaction",
        //   guide: "removal",
        //   backgroundImage: "khm-dream-devourer-david-rapoza",
        //   backgroundCaption: "David Rapoza",
        // },
        {
          slug: "foretell",
          template: "guide",
          guide: "khm-foretell",
          title: "Foretell Guide",
          description: "A guide to all Foretell cards in Kaldheim.",
          icon: "fas fa-eye",
          backgroundImage: "khm-gnottvold-slumbermound-simon-dominic",
          backgroundCaption: "Simon Dominic",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "khm-axgard-cavalry-evyn-fong",
          backgroundCaption: "Evyn Fong",
        },
      ],
    },
    {
      slug: "kaladesh-remastered",
      template: "info",
      preset: "info",
      formatCode: "klr",
      releaseDate: "November 12, 2020",
      backgroundImage: "aer-dawnfeather-eagle-sidharth-chaturvedi",
      backgroundCaption: "Sidharth Chaturvedi",
      pages: [
        {
          slug: "effects",
          template: "guide-group",
          guideGroup: "effects",
          preset: "guide-group-effects",
          backgroundImage: "kld-aetherflux-reservoir-cliff-childs",
          backgroundCaption: "Cliff Childs",
        },
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "kld-skywhalers-shot-chris-rallis",
          backgroundCaption: "Chris Rallis",
        },
        // {
        //   slug: "removal",
        //   template: "guide",
        //   preset: "guide-interaction",
        //   guide: "removal",
        //   backgroundImage: "aer-fatal-push-eric-deschamps",
        //   backgroundCaption: "Eric Dechamps",
        // },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "kld-speedway-fanatic-slawomir-maniak",
          backgroundCaption: "Slawomir Maniak",
        },
      ],
    },
    {
      slug: "zendikar-rising",
      template: "info",
      preset: "info",
      formatCode: "znr",
      releaseDate: "September 25, 2020",
      backgroundImage: "znr-cragcrown-pathway-andreas-rocha",
      backgroundCaption: "Andreas Rocha",
      pages: [
        {
          slug: "effects",
          template: "guide-group",
          guideGroup: "effects",
          preset: "guide-group-effects",
          backgroundImage: "znr-forsaken-monument-piotr-dura",
          backgroundCaption: "Piotr Dura",
        },
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "znr-resolute-strike-zezhou-chen",
          backgroundCaption: "Zezhou Chen",
        },
        // {
        //   slug: "removal",
        //   template: "guide",
        //   preset: "guide-interaction",
        //   guide: "removal",
        //   backgroundImage: "znr-mind-carver-scott-murphy",
        //   backgroundCaption: "Scott Murphy",
        // },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "znr-timbercrown-pathway-andreas-rocha",
          backgroundCaption: "Andreas Rocha",
        },
      ],
    },
    {
      slug: "amonkhet-remastered",
      template: "info",
      preset: "info",
      formatCode: "akr",
      releaseDate: "August 13, 2020",
      backgroundImage: "akr-collected-company-lake-hurwitz",
      backgroundCaption: "Lake Hurwitz",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "akr-pact-of-negation-titus-lunter",
          backgroundCaption: "Titus Lunter",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "akr-hour-of-promise-jonas-de-ro",
          backgroundCaption: "Jonas De Ro",
        },
      ],
    },
    {
      slug: "double-masters",
      template: "info",
      preset: "info",
      formatCode: "2xm",
      releaseDate: "August 7, 2020",
      backgroundImage: "2xm-urzas-tower-mark-tedin",
      backgroundCaption: "Mark Tedin",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "2xm-chord-of-calling-karl-kopinski",
          backgroundCaption: "Karl Kopinski",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "2xm-blightsteel-colossus-chris-rahn",
          backgroundCaption: "Chris Rahn",
        },
      ],
    },
    {
      slug: "core-set-2021",
      template: "info",
      preset: "info",
      formatCode: "m21",
      releaseDate: "June 26, 2020",
      backgroundImage: "m21-baneslayer-angel-greg-staples",
      backgroundCaption: "Greg Staples",
      pages: [
        {
          slug: "effects",
          template: "guide-group",
          guideGroup: "effects",
          preset: "guide-group-effects",
          backgroundImage: "m21-vito-thorn-of-the-dusk-rose-lie-setiawan",
          backgroundCaption: "Lie Setiawan",
        },
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "m21-volcanic-geyser-clint-cearley",
          backgroundCaption: "Clint Cearley",
        },
        // {
        //   slug: "removal",
        //   template: "guide",
        //   preset: "guide-interaction",
        //   guide: "removal",
        //   backgroundImage: "m21-massacre-wurm-jason-chan",
        //   backgroundCaption: "Jason Chan",
        // },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "m21-teferi-master-of-time-yongjae-choi",
          backgroundCaption: "Yongjae Choi",
        },
      ],
    },
    {
      slug: "ikoria-land-of-the-behemoths",
      template: "info",
      preset: "info",
      formatCode: "iko",
      releaseDate: "April 17, 2020",
      backgroundImage: "iko-archipelagore-kev-walker",
      backgroundCaption: "Kev Walker",
      pages: [
        {
          slug: "effects",
          template: "guide-group",
          guideGroup: "effects",
          preset: "guide-group-effects",
          backgroundImage: "iko-lurrus-of-the-dream-den-slawomir-maniak",
          backgroundCaption: "Slawomir Maniak",
        },
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "iko-voracious-greatshark-mathias-kollros",
          backgroundCaption: "Mathias-Kollros",
        },
        // {
        //   slug: "removal",
        //   template: "guide",
        //   preset: "guide-interaction",
        //   guide: "removal",
        //   backgroundImage: "iko-almighty-brushwagg-dmitry-burmak",
        //   backgroundCaption: "Dmitry Burmak",
        // },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "iko-durable-coilbug-milivoj-ceran",
          backgroundCaption: "Milivoj Ćeran",
        },
      ],
    },
    {
      slug: "theros-beyond-death",
      template: "info",
      preset: "info",
      formatCode: "thb",
      releaseDate: "January 17, 2020",
      backgroundImage: "thb-thassa-deep-dwelling-zack-stella",
      backgroundCaption: "Zack Stella",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "thb-allure-of-the-unknown-seb-mckinnon",
          backgroundCaption: "Seb McKinnon",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "thb-thassa-deep-dwelling-zack-stella",
          backgroundCaption: "Zack Stella",
        },
      ],
    },
    {
      slug: "throne-of-eldraine",
      template: "info",
      preset: "info",
      formatCode: "eld",
      releaseDate: "September 28, 2019",
      backgroundImage: "eld-wishful-merfolk-livia-prima",
      backgroundCaption: "Livia Prima",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "eld-swamp-svetlin-velinov",
          backgroundCaption: "Svetlin Velinov",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "eld-wishful-merfolk-livia-prima",
          backgroundCaption: "Livia Prima",
        },
      ],
    },
    {
      slug: "core-set-2020",
      template: "info",
      preset: "info",
      formatCode: "m20",
      releaseDate: "July 5, 2019",
      backgroundImage: "m20-chandra-acolyte-of-flame-anna-steinbauer",
      backgroundCaption: "Anna Steinbauer",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "m20-unholy-indenture-seb-mckinnon",
          backgroundCaption: "Seb McKinnon",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "m20-chandra-acolyte-of-flame-anna-steinbauer",
          backgroundCaption: "Anna Steinbauer",
        },
      ],
    },
    {
      slug: "war-of-the-spark",
      template: "info",
      preset: "info",
      formatCode: "war",
      releaseDate: "April 27, 2019",
      backgroundImage: "war-commence-the-endgame-noah-bradley",
      backgroundCaption: "Noah Bradley",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "war-bolt-bend-svetlin-velinov",
          backgroundCaption: "Svetlin Velinov",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "war-commence-the-endgame-noah-bradley",
          backgroundCaption: "Noah Bradley",
        },
      ],
    },
    {
      slug: "ravnica-allegiance",
      template: "info",
      preset: "info",
      formatCode: "rna",
      releaseDate: "January 19, 2019",
      backgroundImage: "rna-home",
      backgroundCaption: "",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "rna-bedevil-seb-mckinnon",
          backgroundCaption: "Seb McKinnon",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "rna-home",
          backgroundCaption: "",
        },
      ],
    },
    {
      slug: "guilds-of-ravnica",
      template: "info",
      preset: "info",
      formatCode: "grn",
      releaseDate: "September 29, 2018",
      backgroundImage: "grn-home",
      backgroundCaption: "",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "grn-instants",
          backgroundCaption: "",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "grn-home",
          backgroundCaption: "",
        },
      ],
    },
    {
      slug: "core-set-2019",
      template: "info",
      preset: "info",
      formatCode: "m19",
      releaseDate: "July 7, 2018",
      backgroundImage: "m19-home",
      backgroundCaption: "",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "m19-spit-flame-chris-rahn",
          backgroundCaption: "Chris Rahn",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "m19-home",
          backgroundCaption: "",
        },
      ],
    },
    {
      slug: "dominaria",
      template: "info",
      preset: "info",
      formatCode: "dom",
      releaseDate: "April 21, 2018",
      backgroundImage: "dom-knight-of-grace-sidharth-chaturvedi",
      backgroundCaption: "Sidharth Chaturvedi",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "dom-syncopate-tommy-arnold",
          backgroundCaption: "Tommy Arnold",
        },
        // {
        //   slug: "removal",
        //   template: "guide",
        //   preset: "guide-interaction",
        //   guide: "removal",
        //   backgroundImage: "dom-jayas-immolating-inferno-noah-bradley",
        //   backgroundCaption: "Noah Bradley",
        // },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "dom-knight-of-grace-sidharth-chaturvedi",
          backgroundCaption: "Sidharth Chaturvedi",
        },
      ],
    },
    {
      slug: "rivals-of-ixalan",
      template: "info",
      preset: "info",
      formatCode: "rix",
      releaseDate: "January 13, 2018",
      backgroundImage: "rix-home",
      backgroundCaption: "",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "rix-instants",
          backgroundCaption: "",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "rix-home",
          backgroundCaption: "",
        },
      ],
    },
    {
      slug: "ixalan",
      template: "info",
      preset: "info",
      formatCode: "xln",
      releaseDate: "September 23, 2017",
      backgroundImage: "xln-home",
      backgroundCaption: "",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "xln-instants",
          backgroundCaption: "",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "xln-home",
          backgroundCaption: "",
        },
      ],
    },
    {
      slug: "hour-of-devastation",
      template: "info",
      preset: "info",
      formatCode: "hou",
      releaseDate: "July 8, 2017",
      backgroundImage: "hou-home",
      backgroundCaption: "",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "hou-instants",
          backgroundCaption: "",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "hou-home",
          backgroundCaption: "",
        },
      ],
    },
    {
      slug: "amonkhet",
      template: "info",
      preset: "info",
      formatCode: "akh",
      releaseDate: "April 22, 2017",
      backgroundImage: "akh-home",
      backgroundCaption: "",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "akh-instants",
          backgroundCaption: "",
        },
        // {
        //   slug: "removal",
        //   template: "guide",
        //   preset: "guide-interaction",
        //   guide: "removal",
        //   backgroundImage: "akh-removal",
        //   backgroundCaption: "",
        // },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "akh-home",
          backgroundCaption: "",
        },
      ],
    },
    {
      slug: "modern-masters-2017",
      template: "info",
      preset: "info",
      formatCode: "mm3",
      releaseDate: "March 17, 2017",
      backgroundImage: "mm3-home",
      backgroundCaption: "",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "mm3-instants",
          backgroundCaption: "",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "mm3-home",
          backgroundCaption: "",
        },
      ],
    },
    {
      slug: "aether-revolt",
      template: "info",
      preset: "info",
      formatCode: "aer",
      releaseDate: "January 14, 2017",
      backgroundImage: "aer-home",
      backgroundCaption: "",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "aer-instants",
          backgroundCaption: "",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "aer-home",
          backgroundCaption: "",
        },
      ],
    },
    {
      slug: "kaladesh",
      template: "info",
      preset: "info",
      formatCode: "kld",
      releaseDate: "September 24, 2016",
      backgroundImage: "kld-home",
      backgroundCaption: "",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "kld-instants",
          backgroundCaption: "",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "kld-home",
          backgroundCaption: "",
        },
      ],
    },
    {
      slug: "conspiracy-take-the-crown",
      template: "info",
      preset: "info",
      formatCode: "cn2",
      releaseDate: "August 26, 2016",
      backgroundImage: "cn2-home",
      backgroundCaption: "",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "cn2-instants",
          backgroundCaption: "",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "cn2-home",
          backgroundCaption: "",
        },
      ],
    },
    {
      slug: "eldritch-moon",
      template: "info",
      preset: "info",
      formatCode: "emn",
      releaseDate: "July 16, 2016",
      backgroundImage: "emn-home",
      backgroundCaption: "",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "emn-instants",
          backgroundCaption: "",
        },
        // {
        //   slug: "removal",
        //   template: "guide",
        //   preset: "guide-interaction",
        //   guide: "removal",
        //   backgroundImage: "emn-removal",
        //   backgroundCaption: "",
        // },
        {
          slug: "madness",
          template: "guide",
          guide: "madness",
          title: "Madness Guide",
          description: "A guide to madness cards that can be cast when discarded.",
          icon: "fas fa-angry",
          backgroundImage: "emn-madness",
          backgroundCaption: "",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "emn-home",
          backgroundCaption: "",
        },
      ],
    },
    {
      slug: "eternal-masters",
      template: "info",
      preset: "info",
      formatCode: "ema",
      releaseDate: "June 10, 2016",
      backgroundImage: "ema-home",
      backgroundCaption: "",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "ema-instants",
          backgroundCaption: "",
        },
        // {
        //   slug: "removal",
        //   template: "guide",
        //   preset: "guide-interaction",
        //   guide: "removal",
        //   backgroundImage: "ema-removal",
        //   backgroundCaption: "",
        // },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "ema-home",
          backgroundCaption: "",
        },
      ],
    },
    {
      slug: "shadows-over-innistrad",
      template: "info",
      preset: "info",
      formatCode: "soi",
      releaseDate: "April 2, 2016",
      backgroundImage: "soi-home",
      backgroundCaption: "",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "soi-instants",
          backgroundCaption: "",
        },
        // {
        //   slug: "removal",
        //   template: "guide",
        //   preset: "guide-interaction",
        //   guide: "removal",
        //   backgroundImage: "soi-removal",
        //   backgroundCaption: "",
        // },
        {
          slug: "madness",
          template: "guide",
          guide: "madness",
          title: "Madness Guide",
          description: "A guide to madness cards that can be cast when discarded.",
          icon: "fas fa-angry",
          backgroundImage: "soi-madness",
          backgroundCaption: "",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "soi-home",
          backgroundCaption: "",
        },
      ],
    },
    {
      slug: "oath-of-the-gatewatch",
      template: "info",
      preset: "info",
      formatCode: "ogw",
      releaseDate: "",
      backgroundImage: "ogw-home",
      backgroundCaption: "",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "ogw-instants",
          backgroundCaption: "",
        },
        // {
        //   slug: "removal",
        //   template: "guide",
        //   preset: "guide-interaction",
        //   guide: "removal",
        //   backgroundImage: "ogw-removal",
        //   backgroundCaption: "",
        // },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "ogw-home",
          backgroundCaption: "",
        },
      ],
    },
    {
      slug: "battle-for-zendikar",
      template: "info",
      preset: "info",
      formatCode: "bfz",
      releaseDate: "September 26, 2015",
      backgroundImage: "bfz-home",
      backgroundCaption: "",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "bfz-instants",
          backgroundCaption: "",
        },
        // {
        //   slug: "removal",
        //   template: "guide",
        //   preset: "guide-interaction",
        //   guide: "removal",
        //   backgroundImage: "bfz-removal",
        //   backgroundCaption: "",
        // },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "bfz-home",
          backgroundCaption: "",
        },
      ],
    },
    {
      slug: "magic-origins",
      template: "info",
      preset: "info",
      formatCode: "ori",
      releaseDate: "July 11, 2015",
      backgroundImage: "ori-home",
      backgroundCaption: "",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "ori-instants",
          backgroundCaption: "",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "ori-home",
          backgroundCaption: "",
        },
      ],
    },
    {
      slug: "modern-masters-2015",
      template: "info",
      preset: "info",
      formatCode: "mm2",
      releaseDate: "May 22, 2015",
      backgroundImage: "mm2-home",
      backgroundCaption: "",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "mm2-instants",
          backgroundCaption: "",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "mm2-home",
          backgroundCaption: "",
        },
      ],
    },
    {
      slug: "tempest-remasetered",
      template: "info",
      preset: "info",
      formatCode: "tpr",
      releaseDate: "May 6, 2015",
      backgroundImage: "tpr-home",
      backgroundCaption: "",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "tpr-instants",
          backgroundCaption: "",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "tpr-home",
          backgroundCaption: "",
        },
      ],
    },
    {
      slug: "dragons-of-tarkir",
      template: "info",
      preset: "info",
      formatCode: "dtk",
      releaseDate: "March 21, 2015",
      backgroundImage: "dtk-home",
      backgroundCaption: "",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "dtk-instants",
          backgroundCaption: "",
        },
        {
          slug: "megamorphs",
          template: "guide",
          guide: "megamorphs",
          title: "Megamorphs Guide",
          description: "A guide to every possible megamorph in the format.",
          icon: "fas fa-egg",
          backgroundImage: "dtk-megamorphs",
          backgroundCaption: "",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "dtk-home",
          backgroundCaption: "",
        },
      ],
    },
    {
      slug: "fate-reforged",
      template: "info",
      preset: "info",
      formatCode: "frf",
      releaseDate: "January 17, 2015",
      backgroundImage: "frf-home",
      backgroundCaption: "",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "frf-instants",
          backgroundCaption: "",
        },
        {
          slug: "morphs",
          template: "guide",
          guide: "morphs",
          title: "Morphs Guide",
          description: "A guide to every possible morph in the format.",
          icon: "fas fa-egg",
          backgroundImage: "frf-morphs",
          backgroundCaption: "",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "frf-home",
          backgroundCaption: "",
        },
      ],
    },
    {
      slug: "khans-of-tarkir",
      template: "info",
      preset: "info",
      formatCode: "ktk",
      releaseDate: "September 20, 2014",
      backgroundImage: "ktk-home",
      backgroundCaption: "",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "ktk-instants",
          backgroundCaption: "",
        },
        {
          slug: "morphs",
          template: "guide",
          guide: "morphs",
          title: "Morphs Guide",
          description: "A guide to every possible morph in the format.",
          icon: "fas fa-egg",
          backgroundImage: "ktk-morphs",
          backgroundCaption: "",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "ktk-home",
          backgroundCaption: "",
        },
      ],
    },
    {
      slug: "m15",
      template: "info",
      preset: "info",
      formatCode: "m15",
      releaseDate: "July 18, 2014",
      backgroundImage: "m15-home",
      backgroundCaption: "",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "m15-instants",
          backgroundCaption: "",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "m15-home",
          backgroundCaption: "",
        },
      ],
    },
    {
      slug: "rise-of-the-eldrazi",
      template: "info",
      preset: "info",
      formatCode: "roe",
      releaseDate: "April 17, 2010",
      backgroundImage: "roe-home",
      backgroundCaption: "",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "roe-instants",
          backgroundCaption: "",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "roe-home",
          backgroundCaption: "",
        },
      ],
    },
    {
      slug: "mirrodin",
      template: "info",
      preset: "info",
      formatCode: "mrd",
      releaseDate: "September 20, 2003",
      backgroundImage: "mrd-home",
      backgroundCaption: "",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "mrd-home",
          backgroundCaption: "",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "mrd-home",
          backgroundCaption: "",
        },
      ],
    },
    {
      slug: "eighth-edition",
      template: "info",
      preset: "info",
      formatCode: "8ed",
      releaseDate: "July 28, 2003",
      backgroundImage: "8ed-home",
      backgroundCaption: "",
      pages: [
        {
          slug: "instants",
          template: "guide",
          preset: "guide-instants",
          guide: "instants",
          backgroundImage: "8ed-home",
          backgroundCaption: "",
        },
        {
          slug: "gallery",
          template: "guide",
          preset: "guide-gallery",
          guide: "full",
          backgroundImage: "8ed-home",
          backgroundCaption: "",
        },
      ],
    },
  ],
};
